// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8vLFphSB5vq4_wBme67Bd8-CQp_e5w0',
    appId: '1:1055629992606:web:f52527f82f347b3aebd18f',
    messagingSenderId: '1055629992606',
    projectId: 'pawrapets',
    authDomain: 'pawrapets.firebaseapp.com',
    storageBucket: 'pawrapets.appspot.com',
    measurementId: 'G-LQ1VH6GBVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYhDIa7eMuv3SnQotFeOa0NKz-zy_ajdo',
    appId: '1:1055629992606:android:9ca805976048f391ebd18f',
    messagingSenderId: '1055629992606',
    projectId: 'pawrapets',
    storageBucket: 'pawrapets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0RX4FRQUp9ut4T0cAU1j88JpUBvcdZM',
    appId: '1:1055629992606:ios:11cfa93addc6d742ebd18f',
    messagingSenderId: '1055629992606',
    projectId: 'pawrapets',
    storageBucket: 'pawrapets.appspot.com',
    iosBundleId: 'com.pawrapet.pawrapet',
  );
}
